RuleFile = "rules.toml"
LogDirectory = "../../resource/logs/asset_cooker"
CacheDirectory = "Cache"
WindowTitle = "MyAssetCooker"

[[Repo]]
Name = "Tools"
Path = "../../tools"

[[Repo]]
Name = "Engine"
Path = "../../resource"

[[Repo]]
Name = "Application"
Path = "../../../application/resource"

[[Repo]]
Name = "EngineOutput"
Path = "../../cookedResource"

[[Repo]]
Name = "ApplicationOutput"
Path = "../../../application/cookedResource"
