# Google Apps Script Webhookを呼び出すGitHub Actions
name: NoticeUpdateTask
on:
  pull_request:
    types:
      - closed  # Pull Requestがマージされたときにトリガー

jobs:
  process-pr:
    runs-on: ubuntu-latest
    steps:
      - name: NoticeUpdateTask
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
        run: |
          echo "$PR_BODY" > pr_body.txt
          # 正規表現で taskId と status を抽出
          TASK_ID=$(grep -oP '(?<=

\[)[^\s]+' pr_body.txt)
          STATUS=$(grep -oP '(?<=

\[.* )[^\]

]+' pr_body.txt)
          echo "Extracted TASK_ID=$TASK_ID and STATUS=$STATUS"

          # Google Apps Script Webhookを呼び出す
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"taskId\": \"$TASK_ID\", \"status\": \"$STATUS\"}" \
          https://script.google.com/a/macros/g.neec.ac.jp/s/AKfycby4rst-4oyhUiky_fdNWeoAkE4NnTH38DVZI0DBULEQFvBEkO9hwqFPtHHDTOCeEN7y/exec
